"""add_user_profile_fields

Revision ID: a1ed16e7a052
Revises: 6480c7703485
Create Date: 2026-01-03 15:35:07.192168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1ed16e7a052'
down_revision: Union[str, None] = '6480c7703485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribute_items')
    op.drop_table('product_option_items')
    op.drop_table('product_options')
    op.drop_index('ix_product_media_cloudinary_id', table_name='product_media')
    op.drop_table('product_media')
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_approved_lister',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_approved_lister',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_table('product_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alt', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('src', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cloudinary_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_media_pkey')
    )
    op.create_index('ix_product_media_cloudinary_id', 'product_media', ['cloudinary_id'], unique=False)
    op.create_table('product_options',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('product_options_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('option_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='product_options_pkey'),
    sa.UniqueConstraint('product_id', 'option_name', name='product_options_product_id_option_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('product_option_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['product_options.id'], name='product_option_items_option_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_option_items_pkey'),
    sa.UniqueConstraint('option_id', 'item_name', name='product_option_items_option_id_item_name_key')
    )
    op.create_table('attribute_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attribute_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='attribute_items_pkey'),
    sa.UniqueConstraint('attribute_id', 'item', name='attribute_items_attribute_id_item_key')
    )
    # ### end Alembic commands ###
