"""add_payment_status_enum_to_bookings

Revision ID: f93aebd9ac90
Revises: fa3913369356
Create Date: 2026-01-11 00:29:41.738675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93aebd9ac90'
down_revision: Union[str, None] = 'fa3913369356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_settings_id'), 'admin_settings', ['id'], unique=False)
    
    # Create the ENUM type first
    payment_status_enum = sa.Enum('pending', 'verified', 'fake', name='paymentstatus')
    payment_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Add column with default value of 'pending'
    op.add_column('bookings', sa.Column('payment_status', payment_status_enum, nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'payment_status')
    op.drop_index(op.f('ix_admin_settings_id'), table_name='admin_settings')
    
    # Drop the ENUM type
    sa.Enum(name='paymentstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
